name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SonarQube Scanner
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: "sonar.cfamily.build-wrapper-output=bw-output"

    - name: Build and generate the compilation database
      run: |
        build-wrapper-linux-x86-64 --out-dir bw-output make clean all

    - name: Run SonarQube Scanner
      run: |
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
